### ISSUE TITLE
Multiple peers sharing the same public IP

### ISSUE THREAD

**Issue by intjelic** [dswd/vpncloud#106]
Sometimes two of my devices happen to use the same Internet connection, let's say I'm at home, `laptop` and `desktop` are connecting to my VpnCloud network using a peer that always have the same IP and is always reachable (let's call it the *static peer*). In this scenario, I'm able to connect only one device, and with the other one I won't be able to ping any peer. On the static peer, I will get `ERROR - Crypto error: untrusted peer`.

Now, I'm still fairly new to network in general, so I don't know what to think about it. Is it a bug in VpnCloud? Was VpnCloud built with that scenario in mind? Am I doing something wrong or there's another way it should be done ?

For more information, I'm using device type `tun`, with `fix-rp-filter` set to false, and with `mode: normal` on all peers. I'm also using `auto-claim: true` and `ip` to have a different IP per peer. No beacon settings.

Thank you.

**Comment by intjelic** [comment]
On the static peer, the log looks like this:

```
2020-11-01 1:57:24 - INFO - Reading config file '/etc/vpncloud.net'
2020-11-01 1:57:24 - INFO - Opened device vpncloud0
2020-11-01 1:57:24 - INFO - Setting MTU 1427 on device vpncloud0
2020-11-01 1:57:24 - INFO - Configuring device with ip 10.1.1.1, netmask 255.255.255.0
2020-11-01 1:57:24 - WARN - Your networking configuration might be affected by a vulnerability (https://seclists.org/oss-sec/2019/q4/122), please change your rp_filter setting to 1 (currently 2).
2020-11-01 1:57:34 - INFO - Port-forwarding: no router found
2020-11-01 1:57:34 - INFO - Auto-claiming 10.1.1.1/32 due to interface address
2020-11-01 1:57:34 - INFO - Trusted keys not set, trusting only own public key
2020-11-01 1:57:34 - INFO - Crypto speeds: AES128: 864.5 MiB/s, AES256: 865.4 MiB/s, CHACHA20: 924.8 MiB/s
2020-11-01 1:57:34 - INFO - Running process as daemon
```

I'm suspecting line `2020-11-01 1:57:34 - INFO - Auto-claiming 10.1.1.1/32 due to interface address`, shouldn't it be `10.1.1.0/24` ? Because now I'm noticing that I can never have more than 2 peers on the network.

**Comment by intjelic** [comment]
Lmao, I just had to change the static peer to `mode: switch`. Sorry.

That said, I'd love a bit of explanation. Some pointers to where I can get the information about the concepts I'm missing.

**Comment by dswd** [comment]
Hi @intjelic, I am glad it works for you now. However I am at least as confused as you.

VpnCloud should be able to handle multiple nodes sharing the same IP. You should put them on different ports to avoid address conflicts but other than that it should just work fine. I am using a similar setup at home.
The "untrusted peer" error you are seeing is most likely unrelated to your issue. It is a common error you will see when you run a node on a public IP. People will try to connect with all kinds of software to your node and VpnCloud will filter it all out.

The auto-claim of "10.1.1.1/32" is correct. It means, that your node has one single IP address in your VPN network. The netmask of 255.255.255.0 on the interface is essentially 10.1.1.1/24 which means that whole network range belongs to your VPN and your node claims one single IP of that for itself.
Claiming more than one IP is only needed in advanced setups where you want to connect whole networks instead of single nodes.

Changing the mode of your static peer should have nothing to do with this. I have no idea why it fixed it and i guess if you change it back it will also work. Switch mode means that the node will learn new addresses from the packets it sees and for unknown packets it will send them to all of its peers. This is the native mode for TAP devices but unusual for TUN devices.

**Comment by intjelic** [comment]
Thanks for the reply !

I did all sorts of testing this morning (changing the config on different peers and see how it's behaving). Some of the things were working, then stopped working, etc. Given I'm not an expert, I'll just start again tomorrow, from scratch, and will ask you for each step if this is normal or not, so we can debug this step by step (with logs, configs, etc).

For instance, I was able to ping a node where there's a SSH server but I was unable to connect to it via SSH, when I was able to do both (ping + SSH connect) from another node just fine.

Anyway, I'll get back to you shortly :)

**Comment by intjelic** [comment]
Quick question.

Should each "dynamic peer" (laptop and desktop for instance) declare a different port with `listen: xxxx` in the config file ? Because I'm able to reproduce the issue this morning, and yes, as soon as the second dynamic peer connect to the static peer, the connection starts failing on the first connected peer. I often see mismatch of ports in the logs, but it's varying, the error messages also vary, even when I carefully do it again from scratch. Anyway...

Here is what I would get on the static peer. 

```
INFO - Added peer 42.118.xx.yy:34510
INFO - Added peer 42.118.xx.yy:33371
ERROR - Crypto error: Old nonce rejected
ERROR - Crypto error: Failed to decrypt data
ERROR - Crypto error: Failed to decrypt data
ERROR - Crypto error: Failed to decrypt data
ERROR - Crypto error: Failed to decrypt data
```

From the timestamp, I deduce that the first line is the first dynamic peer connecting, then the second line is the second dynamic peer connecting. And later, when I'm pinging from the first dynamic peer, I get the remaining lines, but not always. And also, sometimes, I get two times the same ports, something like this.

```
INFO - Added peer 42.118.xx.yy:34510
INFO - Added peer 42.118.xx.yy:34510
```

Now, if I do the reverse, and I ping the first dynamic peer from the static peer, I will get the following logs on the dynamic peer.

```
INFO - Added peer 128.199.xx.yy:61078
INFO - Ignoring non-init message from unknown peer 128.199.xx.yy:1037
INFO - Ignoring non-init message from unknown peer 128.199.xx.yy:1037
INFO - Ignoring non-init message from unknown peer 128.199.xx.yy:1037
INFO - Ignoring non-init message from unknown peer 128.199.xx.yy:1037
```

The port `61078` the is one that the static peer is listening to. Is port `1037` the virtual port assigned in the VPN network ? Note that I don't understand the concept of port in this context, are they virtual ports?

Now, my very dumb conclusion/question based on intuition. Isn't that all a problem of mismatching ports ? And changing the static peer to switch mode makes it work because at least it's treating them as unknown peer and recreate a connection or some sort ? Lol. Because even if the logs differ every time I try, I often see error messages ignoring `ip:port` when there was never added peers with this `ip:port`. 

Thank you^^
Let me know what I should do at this point to further investigate the issue. Note that I'm a Rust developer and very interested in the technical part of the code base of VpnCloud, I will gladly study the code until I fully understand how that works :) And while I'm here writing those lines, I should also thank you for writing this software. I find it a very neat and cool solutions to the other VPN solutions out there.

**Comment by dswd** [comment]
Hi,

> Should each "dynamic peer" (laptop and desktop for instance) declare a different port with `listen: xxxx` in the config file ? 

Yes, that would be a good idea. If you reuse the same port you might run into problems if both nodes are behind the NAT gateway and the NAT reassigns the same external port.

> The port `61078` the is one that the static peer is listening to. Is port `1037` the virtual port assigned in the VPN network ? Note that I don't understand the concept of port in this context, are they virtual ports?

This is very strange. There are no "virtual ports" in VpnCloud, so I don't know where this 1037 comes from. I assume that this is an actual address used somewhere on your computer. I just have no idea why that application is contacting your server on the VpnCloud port.

> Now, my very dumb conclusion/question based on intuition. Isn't that all a problem of mismatching ports ? And changing the static peer to switch mode makes it work because at least it's treating them as unknown peer and recreate a connection or some sort ? Lol. Because even if the logs differ every time I try, I often see error messages ignoring `ip:port` when there was never added peers with this `ip:port`.

Changing the static peer to switch mode only affects the traffic within the VPN, the "payload traffic". You are experiencing problems on the VpnCloud protocol level which is the wrapper around the VPN traffic. So this setting should not have any impact.

> Let me know what I should do at this point to further investigate the issue. Note that I'm a Rust developer and very interested in the technical part of the code base of VpnCloud, I will gladly study the code until I fully understand how that works :) And while I'm here writing those lines, I should also thank you for writing this software. I find it a very neat and cool solutions to the other VPN solutions out there.

You might try to comment out https://github.com/dswd/vpncloud/blob/master/src/port_forwarding.rs#L106 and recompile the binary for both dynamic peers. I suspect removing the port forwarding bind might lead to your dynamic nodes stealing the external port from each other and causing your problems. For me this does not happen but it might depend on the type of NAT device. If this solves your problem, I will remove that code.

**Comment by intjelic** [comment]
Thanks for the detailed answer, again!

After removing the line `gateway.remove_port(PortMappingProtocol::UDP, port).ok();` on the dynamic peers, it's working.. wonderfully well! 

Not a single error message on all peers.

**Comment by intjelic** [comment]
Is it normal that I'm unable to ping a dynamic peer from another dynamic peer ?

**Comment by intjelic** [comment]
Never mind, Its pinging fine now. That said, it's not always working. I will try in on a longer period of time to really tell.

How about SSH server though ? From one dynamic peer, I'd like to SSH connect to another dynamic peer. I can ping that peer, but SSH connect won't work. Any thoughts ? :)

**Comment by intjelic** [comment]
Oh, but I'm also noticing there are lost packets when pinging.

```
❯ ping 10.1.1.45
PING 10.1.1.45 (10.1.1.45) 56(84) bytes of data.
64 bytes from 10.1.1.45: icmp_seq=1 ttl=63 time=556 ms
64 bytes from 10.1.1.45: icmp_seq=3 ttl=63 time=552 ms
64 bytes from 10.1.1.45: icmp_seq=4 ttl=63 time=556 ms
64 bytes from 10.1.1.45: icmp_seq=5 ttl=63 time=563 ms
^C
--- 10.1.1.45 ping statistics ---
6 packets transmitted, 4 received, 33.3333% packet loss, time 5031ms
rtt min/avg/max/mdev = 551.682/556.633/563.140/4.125 ms
```

```
❯ ping 10.1.1.42
PING 10.1.1.42 (10.1.1.42) 56(84) bytes of data.
64 bytes from 10.1.1.42: icmp_seq=1 ttl=64 time=280 ms
64 bytes from 10.1.1.42: icmp_seq=2 ttl=64 time=284 ms
64 bytes from 10.1.1.42: icmp_seq=3 ttl=64 time=277 ms
^C
--- 10.1.1.42 ping statistics ---
4 packets transmitted, 3 received, 25% packet loss, time 3002ms
rtt min/avg/max/mdev = 276.697/280.116/283.710/2.865 ms
```

Would that have an impact on an SSH connection for example ?

**Comment by dswd** [comment]
Ok so if you have IP connectivity, that shows that on the VpnCloud side everything is setup properly. VpnCloud does not interfere with application protocols like SSH, so if that doesn't work it might be a problem with your application. On ubuntu systems, SSH must be enabled first before it is accessible. Also network applications can be configured to only listen on certain network interfaces which might cause a problem here.

Your packet loss is interesting. VpnCloud should not add packet loss at all, that might just be the normal packet loss of your connection (VpnCloud also does not compensate packet loss). For a TCP based protocol like SSH, packet loss should only slow the connection down and make it hang sometimes but it should not make it impossible to connect.

Also your RTTs are very high. Is this between two nodes on wifi on different continents? Or did you rebuild the VPN without `--release`?

**Comment by intjelic** [comment]
Yes, nodes on different continents. I get the same when pinging their public IP. Also, I built with `--release`.

> On ubuntu systems, SSH must be enabled first before it is accessible. Also network applications can be configured to only listen on certain network interfaces which might cause a problem here.

Sorry, I wasn't clear. I can SSH connect from the static peer to the dynamic peers,  but I can't SSH connect from one dynamic peer to another dynamic peer. The SSH servers are indeed running and listening on all interfaces for now.

> Your packet loss is interesting. VpnCloud should not add packet loss at all, that might just be the normal packet loss of your connection (VpnCloud also does not compensate packet loss).

Hmm... I seem to be able to ping the public IPs without packet loss, but I suppose it depends on the state of the network which can change. I'll do it several time during the day tomorrow and post the result here.

> For a TCP based protocol like SSH, packet loss should only slow the connection down and make it hang sometimes but it should not make it impossible to connect.

Yeah, that makes sense.

**Comment by intjelic** [comment]
Could it be about TTL not high enough ? Since they have to go back en forth from different continents ?

**Comment by intjelic** [comment]
And for your information, it's not so stable. Throughout the day, some peers become unreachable and I see a lot of errors in the logs. 

On the static peer, errors are mostly `Crypto error: Failed to decrypt data`, `Invalid crypto state: Crypto core not ready yet` and `Ignoring non-init message from unknown peer xxxx.xx.xx:xxxx`.

On the dynamic peers, errors are repeatedly `Closing pending connection to xx.xx.xx.xx:xxxx due to error in crypto init`, and this happens after a peer is forgotten due to timeout, and is added back.

But one thing at a time :)

**Comment by dswd** [comment]
> Could it be about TTL not high enough ? Since they have to go back and forth from different continents ?

No I think that is not relevant here. VpnCloud does not modify the TTL and due to the VPN the connection is a single hop, so TTL should not matter.
I frankly see no reason based in VpnCloud why you are able ping but not connect on TCP level. You could try to increase the logging level of VpnCloud, of your SSH client and even run tcpdump to see what is going on on the wire.
