### ISSUE TITLE
RFE: Local fallback addresses in addition to public addresses for peers

### ISSUE THREAD

**Issue by justindarby** [dswd/vpncloud#122]
Hello,

I have an environment where several clients are behind NAT routers that will not allow the local network to connect to the routers own public IP, period. So even with a centralized publicly accessible peer, they can discover the peers on the same local network, but can't connect to local peers on the local routers public address (even with each using a unique port). I'm currently working around this by using Linux interface forwarding on the central server's vpnCloud interface but this causes clients on the same local network to relay traffic through the central server. The provider of these routers is a relatively large cable internet provider in the United States.

It would be nice if it were possible to additionally specify that the local default gw interface address should be sent as as a falback address to the public address. That way when clients are on the same local network in this situation, they can try to fall back to those addresses to try to discover each other. In an absolute ideal case both automatically detected and manual lists of prioritized local addresses could be provided by a system in the mesh if desired. 

I'd be happy to take a look at this if you're busy, it doesn't appear to be possible to do anything like this in currently released software without a lot of superfluous peer entries, however, I have no experience with rust. I do grok C/Ruby/JavaScript/etc though so it's probably not much of a curve. 

Is this a worthwhile enhancement?

**Comment by dswd** [comment]
Hi Justin,

what you describe is the intended behavior. Nodes determine their private IP as well as the public IP (from the NAT gateway) and publish both addresses. Their peers should store those addresses and pass them on to other nodes in the network, so they can use the private addresses to connect.
I thought I implemented it this way. Maybe you found a bug. I am not sure I can look into it today, but likely this weekend.

BTW: Thanks a lot for the donation and the kind words, if that was you. It really means a lot to me.

**Comment by dswd** [comment]
I checked it and found out that I actually did not implement this feature.

My latest commit contains the missing code. Can you check whether it works for you?

**Comment by justindarby** [comment]
Latest commit works just fine; nodes running this release successfully discover local addresses of peers.

That was me, and no problem. This is good software and much less overhead to maintain than wireguard, it's very helpful.

**Comment by justindarby** [comment]
As an aside, I'm actually wondering if this is why #106 is failing.
