### ISSUE TITLE
Offer strong security

### ISSUE THREAD

**Issue by dswd** [dswd/vpncloud#14]
Currently VpnCloud offers per-message security, which protects each message individually but leaves some attack vectors open. Strong security could include:

* **Public/private keys instead of shared secret.** This should make the system more robust and allow a more fine-grained trust control. On the downside, creating and exchanging key pairs for networks with dozens of nodes is a pretty tedious task.

* **Forward secrecy.** This would protect the communication from an attacker who records it and spends lots of time (or using cipher weaknesses yet to be found) breaking the encryption after it happened. AFAIK, forward secrecy involves ephemeral keys for each node pair (e.g. ECDH). On the downside, this defeats the current "encrypt once, send often" strategy for broadcasts.

* **Protection of stream of messages.** Currently only single messages are encrypted, which leaves us open for attacks on the stream (suppressing messages, reordering messages, duplicating/replaying messages). Any scheme that somehow connects the messages should not require ordered delivery (this can't be guaranteed in UDP with high rates) or acknowledgments (this would significantly affect performance).

As I am not an expert in this field, I am putting my thoughts here for any expert to comment and offer solutions and maybe for developers to volunteer.

**Comment by jpastuszek** [comment]
Some ideas (I am not an expert but I did some VPN setups before):
* __Public/private keys instead of shared secret__ - here you can do two things: 
  * use plain public/private keys (this is what gvpe VPN uses) and let users use some other tool to exchange all public keys with all the nodes (e.g. Puppet, Chef etc.)
  * you can send node's certificate (that includes the public key) during initialisation and verify it was signed by per-exchanged Certificate Authority certificate and was not listed in Certificate Revocation List - this is how IPSec IKE works - this way you don't need to change anything on existing nodes when adding more nodes to the network but it requires some sort of PKI setup to make and sign certificates for new nodes

**Comment by dswd** [comment]
I think I would go with a full set of exchanged public keys. This sounds easier to set up than CA + CRL.

**Comment by tarcieri** [comment]
I would strongly suggest you take a look at [WireGuard](https://www.wireguard.io/) for protocol ideas. It's a modern implementation of a VPN based on the [Noise Protocol](http://www.noiseprotocol.org/).

**Comment by dswd** [comment]
My current plan on this topic (if I ever find time to actually implement it) is the following:
1) **Add a crypto scheme similar to WireGuard's/Noice protocol as an option.** This is actually a lesser change than I thought because VpnCloud already encrypts using ChaCha20+Poly1305 and I would just have to add a key exchange in the handshake and a key rotation based on Curve25519. It is unavoidable that this results in different symmetric keys for each peer pair and thus, broadcasts have to be encrypted multiple times. This is not as big a problem as I initially thought, as a) broadcasts are rare in normal setups and b) the messages need to be decrypted by each peer seperately anyways, so the effort for encryption and decryption becomes symmetric.
2) **Derive asymmetric key pairs from the password by default.** The result is that all peers with the same password have the same key pair and thus trust each others by default. This makes the above encryption feasible for large setups as no key exchange/signing is needed.
3) **Add public/private key mode as an option.** In this mode, the node only trusts a given set of public keys. This requires explicit key exchange but increases security (by being password-less) and trust control (exclude one peer without having to change the password on all nodes).
4) **Add an option for transitive trust.** If this option is enabled, nodes publish the public keys of their peers with their node lists and trust all public keys received from a trusted peer. This makes more complicated setups with introducer nodes possible.

I am not sure I can implement this without changing the message format and requiring a message format version change. However in the end, the impact of such a version change is unavoidable as nodes using different crypto method can not and should not be able to communicate. Also there should not be any kind of negotiation of crypto methods like in SSL/TLS since this will open a whole new attack vector.

Again, I put this out there so that any expert can verify and comment on the plan before I actually implement it (eventually).

**Comment by XVilka** [comment]
Are there any updates on this?

**Comment by dswd** [comment]
No, not yet. I think this is more a plan for version 2 while I am focusing on 1.0 right now.

**Comment by dswd** [comment]
Implemented in upcoming version 2
