### ISSUE TITLE
debian gpg key expired

### ISSUE THREAD

**Issue by xiezhuojin** [dswd/vpncloud#160]
I followed the tutorial on https://vpncloud.ddswd.de/install/ to install vpncloud, but I got a signature invalid error while I do apt update. This is the output of apt-key list
```
pub   rsa3072 2019-02-13 [SC] [expired: 2021-02-12]
      84C3 5E01 CC81 773E 5AE0  D910 DE4A C96B 587C 93A9
uid           [ expired] Dennis Schwerdel (Repo Key) <schwerdel@googlemail.com>

/etc/apt/trusted.gpg.d/debian-archive-buster-automatic.gpg
```

**Comment by mtarekcse** [comment]
Yes, I am here to report the same issue.

**Comment by dswd** [comment]
I removed the expiration date from the key (wasn't even aware I set one). Sorry for that.
