### ISSUE TITLE
vpncloud does not listen

### ISSUE THREAD

**Issue by vrogojin** [dswd/vpncloud#22]
Vpncloud will not listen to port 3210, even when explicitly indicated.
I used command `vpncloud --config /etc/vpncloud/vrogojin.net -l 3210`, where vrogojin.net is configured as a gateway from tutorial https://github.com/dswd/vpncloud.rs/wiki/Dial-in-Tutorial.
Clearly, without that function its is not possible to build VPN, since at least one vpn node with open port must be working

**Comment by dswd** [comment]
Does the problem still exist?
If so, please provide complete verbose logging via `-v`.
