### ISSUE TITLE
Would be nice to have release package for 0.9.x compatible with older Ubuntu

### ISSUE THREAD

**Issue by mobiletradingpartners** [dswd/vpncloud#24]
Not sure if this is an "issue" or just something that needs documenting better.

It's not possible to install the latest deb packages on Ubuntu 16.04 (probably on 18.04 as well) even when upgrading to libgcc-8-dev etc.

I have reverted to 0.8.1 for the time being, and that installs fine of course.

Would be wonderful if the release packages could include the older LTS versions though.

**Comment by dswd** [comment]
I created the packages on Ubuntu 18.04 and was not aware of the problem. I still have one machine with 16.04 and will build one package for you.
For future versions, I can not guarantee compatibility with 16.04 as want to upgrade that machine too.
Maybe I can work with Daocker...

**Comment by dswd** [comment]
Here you go: https://github.com/dswd/vpncloud/releases/download/v0.9.1/vpncloud_0.9.1_xenial_amd64.deb

**Comment by mobiletradingpartners** [comment]
Thank you! I wasn't expecting such a quick resolution :)

Installed and running, it works.
