### ISSUE TITLE
ArchLinux - "failed to open virtual tap interface vpncloud%d"

### ISSUE THREAD

**Issue by XVilka** [dswd/vpncloud#27]
I have ArchLinux minimal installed, then compiled vpncloud from sources, no additional packages were installed, except required for building. Copied systemd unit file and tried to start.
It failed to start with the following error:
```
ERROR - Failed to open virtual tap interface vpncloud%d: No such device (os error 19)
```

I used this article as a howto for setting it up: https://medium.com/@matteocontrini/how-to-setup-a-peer-to-peer-fully-meshed-vpn-between-servers-249a9071e714

**Comment by dswd** [comment]
Hello, just to check the simple causes:
* Are you running this as root?
* Does /dev/net/tun exist on your system?

**Comment by XVilka** [comment]
Yes, as root and `/dev/net/tun` exists.

**Comment by XVilka** [comment]
Note it is specific to ArchLinux, the rest of my nodes are Ubuntu and they started successfully with the same configuration file.

**Comment by dswd** [comment]
Cloud you try to run it in debug mode, i.e. `-v` and paste the output?

**Comment by dswd** [comment]
While searching for your problem I stumbled upon a similar issue. Could it be that you upgraded the kernel without rebooting? That seems to be an issue on Arch Linux.

**Comment by XVilka** [comment]
Ah, exactly this, I did upgrade the kernel without rebooting. Rebooting
fixed this.
