### ISSUE TITLE
Provide 0.9.x package for Debian Stretch

### ISSUE THREAD

**Issue by Southparkfan** [dswd/vpncloud#28]
Similar to issue #24, just the same for Debian 9. When Debian 10 is released as stable I will upgrade of course, but for now a package would be great!

**Comment by dswd** [comment]
I am working on a setup that uses docker to build for different Debian/Ubuntu versions.

**Comment by dswd** [comment]
Oh, did you try the package for Ubuntu 16.04? It might work as there is nothing Debian/Ubuntu specific in it.

**Comment by Southparkfan** [comment]
Hi, sorry for the delay. I will try the package soon. Thanks for your help!

**Comment by Southparkfan** [comment]
The package seems to work perfectly on Debian 9. We're still looking forward to the docker solution :)

**Comment by dswd** [comment]
I already implemented the docker builder. Please look into the folder "builder"
