### ISSUE TITLE
Ability to disable UPnP

### ISSUE THREAD

**Issue by XVilka** [dswd/vpncloud#31]
Since UPnP is often a vulnerability by design, it would be awesome to have the option to disable it in the config.

**Comment by dswd** [comment]
Please use `--no-port-forwarding` or `port_forwarding: false` in the config

**Comment by XVilka** [comment]
Thanks, solved. You might want to add the option in the example config: https://github.com/dswd/vpncloud/blob/master/assets/example.net.disabled
