### ISSUE TITLE
The binary build by myself can't automaitc set TUN IP Correctly

### ISSUE THREAD

**Issue by Handsome1080P** [dswd/vpncloud#335]
I had built by mysel with latest RUST,configrations below:

- Server

> mode: normal
listen: 5000
ip: 10.88.0.1
port-forwarding: false
peer-timeout: 300
keepalive: 25
device:
  name: tun0
  type: tun
  fix-rp-filter: false
claims: - 0.0.0.0/0
 crypto: password: "634218"

- Client

> mode: normal
ip: 10.88.0.2
port-forwarding: false
peer-timeout: 300
keepalive: 25
device:
  name: tun0
  type: tun
  fix-rp-filter: false
crypto:password: "634218"
peers: - 192.168.250.110:5000

- AND TUN IP always not correct,0.0.1.0 and 0.0.2.0

![image.png](https://s2.loli.net/2022/10/23/EqiaktD9eXbVFry.png)
![image.png](https://s2.loli.net/2022/10/23/MCKJZbOQsfahNYc.png)

- Debug logs:

![image.png](https://s2.loli.net/2022/10/23/kaYLPEAg34BKNOf.png)

**Comment by paluszak** [comment]
I have exactly the same problem, vpncloud built with 1.64.0

**Comment by Handsome1080P** [comment]
> I have exactly the same problem, vpncloud built with 1.64.0

any solutions?

**Comment by dswd** [comment]
Hi there,
it seems that libc changed something recently. I fixed that issue in a different branch already but did not have the time to port the fix to the master version (I am working on a multithreaded version which will replace master sometime soon). Here is the  commit of the fix: [ca4ad2769dc9be1a027bb15cc56f63a1906d6dc7](https://github.com/dswd/vpncloud/commit/ca4ad2769dc9be1a027bb15cc56f63a1906d6dc7).

**Comment by Handsome1080P** [comment]
> Hi there, it seems that libc changed something recently. I fixed that issue in a different branch already but did not have the time to port the fix to the master version (I am working on a multithreaded version which will replace master sometime soon). Here is the commit of the fix: [ca4ad2769dc9be1a027bb15cc56f63a1906d6dc7](https://github.com/dswd/vpncloud/commit/ca4ad2769dc9be1a027bb15cc56f63a1906d6dc7).

Thx a lot
