### ISSUE TITLE
What is Purpose or Use-case for Magic ID

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#35]
re Documentation says...

Magic ID -

Override the 4-byte magic header of each packet. This header identifies the network and helps to distinguish it from other networks and other applications. The id can either be a 4 byte / 8 character hexadecimal string or an arbitrary string prefixed with "hash:" which will then be hashed into 4 bytes.

Is this Magic ID used similarly to a VXLAN VNI (Virtual Network Identifier) or a BGP AS (Autonomous System number) to ID a specific VPN “group” of servers from perhaps other VPN “groups” of servers that the VpnCloud is also managing?

Is there any example config file for VpnCloud w/more than one VPN configured?

I just want to be sure I would be setting all required fields in the config.

FYI.. I will be using it with Ubuntu 18.04 and LXD containers for multi-site, multi-tenant support if all works out.

Thanks for any insight…

Brian

**Comment by dswd** [comment]
The magic header is the 4 byte header of every packet that VpnCloud sends. I made it configurable in case someone needs it. Right now, the use cases are very limited:

1) In some countries traffic is controlled and monitored and VPNs are not allowed. It would be pretty easy to block VpnCloud traffic if all packets had the same 4 magic bytes as a header.

2) If you are reusing IPs frequently (e.g. in a very volatile and virtualized environment) and use the same encryption settings for multiple networks (or none at all) it could happen that a peer of network A still has an IP cached that is now part of network B. Then those networks will merge without you intending so. Different magic headers will avoid this problem.

VpnCloud has no functionality to run multiple networks in a single instance and there are currently no plans to implement this functionality. Any such implementation would require a lot of work to be fast and secure and in the end the only use case to me is sharing a single port number. VpnCloud can run on any port number and there usually is no shortage on port numbers.

**Comment by bmullan** [comment]
Thanks for the answer.

So if I read it correctly, to support multi-client I'd have to run one instance of VpnCloud for each Customer and each using a different Port number.

**Comment by bmullan** [comment]
Thanks for the answer.

So if I read it correctly, to support multi-client I'd have to run one instance of VpnCloud for each Customer and each using a different Port number.

Can I have a separate config file for each?   
I don't recall reading if that was available or not.

**Comment by bmullan** [comment]
Thanks for the answer.

So if I read it correctly, to support multi-client I'd have to run one instance of VpnCloud for each Customer and each using a different Port number.

Can I have a separate config file for each?   
I don't recall reading if that was available or not.

**Comment by dswd** [comment]
Sure, you can have multiple configs in `/etc/vpncloud`. If you are calling VpnCloud as a command you can call reference those files via `--config` parameters (see https://github.com/dswd/vpncloud/blob/master/vpncloud.md#options). If you are using it as a service, you can reference `/etc/vpncloud/clientX.net` as `vpncloud@clientX` (see https://github.com/dswd/vpncloud/blob/master/assets/example.net.disabled#L6)

**Comment by bmullan** [comment]
Thanks for your guidance !

Brian
