### ISSUE TITLE
Help with autostart on Debian 10 Buster

### ISSUE THREAD

**Issue by ghost** [dswd/vpncloud#36]
Hello everyone,
can anyone help me troubleshoot why vpncloud service wont start on startup but fails with 'timeout'?
when trying to start service manually service starts without any problem.
After manual start on both nodes i can ping servers trough vpncloud IPs.
Both nodes are running Debian 10 Buster, autostart fails on both nodes.
I did set user and group under which it should run in background (root).

Thanks for any help!

● vpncloud@vpslink.service - VpnCloud network 'vnet'
   Loaded: loaded (/lib/systemd/system/vpncloud@.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Sun 2019-10-27 20:00:22 GMT; 2min 4s ago
  Process: 545 ExecStart=/usr/bin/vpncloud --config /etc/vpncloud/vnet.net --daemon --log-file /var/log/vpncloud-vnet.log --stats-file /var/log/vpncloud-vnet.stats --pid-file /run/vpncloud-vnet.pid (code=killed, signal=TERM)

Oct 27 19:58:51 server1 systemd[1]: Starting VpnCloud network 'vnet'...
Oct 27 19:58:52 server1 vpncloud[545]: INFO - Reading config file '/etc/vpncloud/vnet.net'
Oct 27 19:58:52 server1 vpncloud[545]: INFO - Opened device vnet0
Oct 27 20:00:22 server1 systemd[1]: vpncloud@vpslink.service: Start operation timed out. Terminating.
Oct 27 20:00:22 server1 systemd[1]: vpncloud@vnet.service: Control process exited, code=killed, status=15/TERM
Oct 27 20:00:22 server1 systemd[1]: vpncloud@vnet.service: Failed with result 'timeout'.
Oct 27 20:00:22 server1 systemd[1]: Failed to start VpnCloud network 'vnet'.

**Comment by bmullan** [comment]
I use ubuntu 18.04 and LXD containers.
I wanted to use VpnCloud to create a full mesh overlay network to interconnect the bridge on each LXD Server/Hosts.

I read and followed info from one of the VpnCloud examples:

"How to set up a peer-to-peer fully-meshed VPN between servers"

https://medium.com/@matteocontrini/how-to-setup-a-peer-to-peer-fully-meshed-vpn-between-servers-249a9071e714

Had you read this yet?   The writeup does talk about the startup config steps.

Maybe it will help you

**Comment by dswd** [comment]
Hi @rmntkc,
sorry for the delayed answer, I was on vacation.
Did the post by @bmullan solve the issue for you?

**Comment by Chrisi-Bavaria** [comment]
Hello all,
I had a look into matteocontrini's post, but I still face the same issue on Debian Buster: 
systemctl start works fine.
systemctl enable creates the symlinks without error.
But the automatic start during boot does not work.
I'll have a look into the looks and compare it to some Ubuntu installation in my network.

**Comment by Chrisi-Bavaria** [comment]
Hi again,

symlink is created at /etc/systemd/system/multi-user.target.wants/vpncloud@mynet.service

Debian Buster shows the following logs:

Dec 03 20:20:07 cubietruck systemd[1]: Starting VpnCloud network 'mynet'...
Dec 03 20:20:08 cubietruck vpncloud[578]: INFO - Reading config file '/etc/vpncloud/mynet.net'
Dec 03 20:20:08 cubietruck vpncloud[578]: INFO - Opened device vpncloud0
Dec 03 20:20:08 cubietruck vpncloud[578]: ERROR - Port-forwarding: failed to find router: IO error: Network is unreachable (os error 101)
Dec 03 20:20:08 cubietruck vpncloud[578]: ERROR - Failed to send message to server4.mynet.de:3210: failed to resolve name '"server4.mynet.de:3210"'
Dec 03 20:20:08 cubietruck systemd[1]: vpncloud@mynet.service: Control process exited, code=exited, status=255/EXCEPTION
Dec 03 20:20:08 cubietruck systemd[1]: vpncloud@mynet.service: Failed with result 'exit-code'.
Dec 03 20:20:08 cubietruck systemd[1]: Failed to start VpnCloud network 'mynet'.

...so it's indeed a different issue. At multiuser-target the network should already be ready, right?

**Comment by dswd** [comment]
Yes, the network should be up and running.
Please also check the latest version as it changes multi-user.target to network-online.target for an unrelated reason.

**Comment by Chrisi-Bavaria** [comment]
Updated today: 

$ vpncloud -V
VpnCloud v1.1.0, protocol version 1

$ systemctl disable vpncloud@mynet
Removed /etc/systemd/system/multi-user.target.wants/vpncloud@mynet.service.

$ systemctl enable vpncloud@mynet
Created symlink /etc/systemd/system/multi-user.target.wants/vpncloud@mynet.service → /lib/systemd/system/vpncloud@.service.

-- I see no change here.

**Comment by bmullan** [comment]
I'm using my phone to answer here but this sounds similar to your problem doesnt it?

> Service unable to start at boot time - Unix & Linux Stack Exchange

https://unix.stackexchange.com/questions/502371/service-unable-to-start-at-boot-time

**Comment by dswd** [comment]
@Chrisi-Bavaria 
To me it seems like your DNS does not come up right at boot time. To check this, please
1) Use an IP address instead of the hostname, or
2) Add this line to [Service] `ExecStartPre=/bin/bash -c 'until host example.com; do sleep 1; done'`

**Comment by Chrisi-Bavaria** [comment]
Hi,
even without manually adding this condition, it is magically working on all nodes. Either the changes on your startup-script in one of the last releases or changes on Debian side fixed the issue.
Do you still face the issue @rmntkc ?

**Comment by dswd** [comment]
I think this has been resolved
