### ISSUE TITLE
Can VpnCloud be configured for multiple VPNs

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#38]
I use Ubuntu and LXD containers and already have gotten VpnCloud to work across multiple clouds to link LXD containers hosted on Server/Instances on those clouds.

However, my Use-Case eventually resembles the following diagram and would involve a multi-tenant, multi-host/node/server, multi-cloud/hybrid environment.

So for the Multi-Tenant connectivity shown in the diagram **_can VpnCloud be used to implement a separate VPN Mesh for each Tenant_**?   

Can multiple instances of VpnCloud be run in a Server and each instance use a different Config & TAP/TUN interface?    Any suggestions for how best to approach this?

Click on the Diagram to enlarge it...

![CIAB Overview Diagram vpncloud](https://user-images.githubusercontent.com/1682855/70196624-5f3f8700-16d7-11ea-9228-62e29a0f25d2.png)

**Comment by dswd** [comment]
Yes, this is absolutely possible with VpnCloud. Actually, it is what VpnCloud has initially been developed and used for. I used VpnCloud to provide the network virtualization of a network research lab. Every researcher could design its own environment which would then be implemented automatically as VMs (KVM and OpenVZ) connected by multiple VpnCloud meshes.
To achieve this setup you would run multiple VpnCloud nodes on each host, one per virtual network. Of course the nodes need different names, different config files and different ports. I would also advise you to either use different shared keys or (if unencrypted) at least different magic headers.
You would then assign the virtual interfaces of the VPN to the VMs of a tenant using LXD and voila, you got a VPN mesh per tenant.
If you need further case-specific help, I can offer you support on an hourly basis.

**Comment by bmullan** [comment]
@dswd 
Thanks so much for your reply.  Given the documentation available I suspected that running multiple instances of VpnCloud, each with its own configuration was the answer but it never hurts to ask in case there was some other way to accomplish this via a single config & single instance means.

I'll set this up and let you know how it works!

By the way... so far I've looked into several possible "solutions" besides VpnCloud and VpnCloud still comes back to the best overall.

I looked at Slack's Nebula which they open sourced last week.   It uses Curve as does WireGuard but Nebula only supports L3 (TUN) from what I can tell from my test of it.

WireGuard seems to work really well, uses Curve but as weill Nebula, WireGuard is only L3 although with both of the above you could configure vxlan or gretap over wireguard/nebula and then connect to the LXD container bridge on each host but then that just adds complexity & overhead.

Some FYI...
I posted about VpnCloud a couple times on Reddit:

https://www.reddit.com/r/linuxadmin/comments/d0gt89/vpns_ive_been_comparing_wireguard_and_vpncloud/

and a follow-up comment I made about the 2 project's posted performance testing numbers where the slight advantage of WireGuard "might be" explained by...

> I also think some of the performance difference was that the VpnCloud tests were done using a Intel Core i5-2540M CPU @ 2.60GH and Intel Core i5-3450 CPU @ 3.10GHz
> 
> whereas the WireGuard tests say they used Intel Core i7-3820QM and Intel Core i7-5200U.

Also, I am the moderator of both [the LXC sub-reddit](https://www.reddit.com/r/LXC/) and **[the LXD sub-reddit](https://www.reddit.com/r/LXD/)** and once I complete my config with VpnCloud I will post a "how-to" on the LXD sub-reddit as I myself focus my use on LXD now-a-days.

Wanted to say thank you though for your great work on VpnCloud.   The more I research "mesh" vpn's the more I appreciate all of the fore-thought you put into VpnCloud's design & implementation!

**Comment by dswd** [comment]
Thanks a lot! Please keep me informed on your posts/turorials as I will link them on the VpnCloud page.

You are right, that you have to run multiple instances of VpnCloud. There is no way to configure one VpnCloud instance to run multiple networks. I thought about this but went against it, as it brings more complexity and costs performance just to save UDP ports.

Talking about the wireguard performance comparison (I didn't know that reddit post): Wireguard has an extreme advantage, that should give it a solid performance lead: It has a kernel module that does the performance critical stuff in kernelspace without context switches while VpnCloud is userspace-only and has to do those context switches. Seeing VpnCloud still perform so well in comparison is great.

**Comment by bmullan** [comment]
@dswd 
I will update you as I get things setup.

Also, although Nebula nor VpnCloud were part of their white paper this research team from University of Ghent published results from testing WireGuard, OpenVPN, TINC, SoftEther, ZeroTier) that were quite interesting.    I did recently send an email to the group asking if they ever revisit the testing to please include Nebula and VpnCloud.

[Scalability Testing Results - Mesh VPN technologies.pdf](https://github.com/dswd/vpncloud/files/3928044/Scalability.Testing.Results.-.Mesh.VPN.technologies.pdf)

**Comment by bmullan** [comment]
@dswd 
Dennis I had written an email to the Researchers at Gent that had produced the White Paper:

[Scalability Testing Results - Mesh VPN technologies.pdf](https://github.com/dswd/vpncloud/files/3951264/Scalability.Testing.Results.-.Mesh.VPN.technologies.pdf)

Today I got a great email back and want to share it with you because of VpnCloud.   Send me an email and I'll forward it to you:   bmullan.mail@gmail.com
