### ISSUE TITLE
VPNCloud on Ubuntu 16.04 - Errors with Dependencies

### ISSUE THREAD

**Issue by menthughes** [dswd/vpncloud#39]
vpncloud on a Ubuntu box - installed using the vpncloud_1.1.0_amd64.deb file (dpkg -i vpncloud_1.1.0_amd64.deb) - complains of the following:

Depends: libgcc1 (>= 1:6.3.0) but 1:6.0.1-0ubuntu1 is installed
Depends: libc6 (>= 2.24) but 2.23-0ubuntu11 is installed

Because of this, apt upgrade also wants to remove this package for having unmet dependencies. However, I'm unsure if vpncloud will work without these being met? It appears like it may do. Can/should the dependencies be changed to work with 16.04 (which I don't believe has an upgrade path to the very-latest versions of libc?)

**Comment by dswd** [comment]
Hi please try https://github.com/dswd/vpncloud/releases/download/v1.1.0/vpncloud_1.1.0_xenial_amd64.deb
I also changed to build process to be based on xenial for future releases.

**Comment by menthughes** [comment]
Thank you! That appears to have installed fine!

Thanks again
