### ISSUE TITLE
Dramatische Performance-Einbruch mit der default-Konfiguration

### ISSUE THREAD

**Issue by DanielFuchs98** [dswd/vpncloud#40]
Hallo *,
ich habe VPNCloud auf zwei virtuellen Debian-Maschinen (Hyper V) nach der Anleitung https://vpncloud.ddswd.de/docs/tutorial-point-to-point/ installiert. Sprich default-Einstellungen bis auf die IP-Adressen, die sich natürlich unterscheiden.

Dann habe ich mittels iperf (https://iperf.fr/) die Verbindung zwischen den beiden Maschinen getestet:

Verbindung über den HyperV-Switch: 
[  3] local 172.17.167.220 port 38824 connected with 172.17.167.216 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  8.82 GBytes  7.57 Gbits/sec

Verbindung über VPNCloud:
[  3] local 10.0.0.1 port 50662 connected with 10.0.0.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   697 MBytes   584 Mbits/sec

Dabei ist die Bandbreite dramatisch gesunken (von knapp 7,5Gbits auf 584Mbits).
Einen geringeren Durchsatz hatte ich erwartet, allerdings nicht in dieser Größe. Gibt es Möglichkeiten, die Verbindung zu optimieren?

Viele Grüße
Daniel Fuchs

**Comment by dswd** [comment]
Hallo Daniel,

leider sind 584 Mbit/s in dem zu erwartenden Bereich. Wenn du nahe an die 7,5 GBit/s kommen willst, solltest du eine höhere MTU nehmen (z.B. 14000) und die Verschlüsselung deaktivieren.

Aber selbst dann solltest du nicht in die Nähe von 7,5 Gbit/s kommen (der Endwert würde mich aber trotzdem interessieren). Die Kommunikation zwischen zwei VMs ohne VPN ist so wenig Aufwand, dass du ohne VPN immer viel schneller bist als mit.
Hast du schon mal andere VPNs getestet? Die sollten auch nicht viel schneller sein. In der Regel schneidet VpnCloud immer relativ gut im Vergleich ab.


LG

Dennis

**Comment by DanielFuchs98** [comment]
Hallo Dennis,

danke für deine schnelle Antwort. Gerne probiere ich die größeren Pakete aus und schreibe die Ergebnisse ins Issue.

Das die Verbindung über den virtuellen Switch ohne Verschlüsselung usw deutlich schneller ist ist klar - für mich ist das auch nur ein Versuchsaufbau gewesen. Am Ende möchte ich mehrere angemietete Server über das Internet verschlüsselt verbinden, aber wenn die Kommunikation dann so extrem gedrosselt wird muss ich nach weiteren alternativen gucken - ob die dann performanter sind als VPNCloud wird sich zeigen.

Danke nochmals und viele Grüße
Daniel

**Comment by dswd** [comment]
Hi Daniel,

in deinem Szenario solltest du die Verschnlüsselung aktiviert lassen. Dann wirst du aber nicht viel besser als 600 - 700 MBit/s werden können.
Für eine verschlüsselte Verbindung ist das aber nicht so schlecht. Bitte beachte, dass der Zusammenhang zwischen der VpnCloud-Performance und der nativen Performance kein fester Faktor ist. D.h. VpnCloud wird bei langsameren Verbindungen (z.B. bei 500 MBit/s nativ) nicht automatisch viel schlechter sein. Also keine Angst, es würde dann nicht 50 Mbit/s werden. Ich rechne dann eher so mit 450 Mbit/s.
Verschlüsselung ist generell sehr aufwändig und ich bezweifle, dass andere Software da deutlich schneller sein kann. Ich gehe eher davon aus, dass VpnCloud in diesem Szenario eine der schnellsten Software ist.
Mach am besten mal ein paar Experimente mit anderen Tools und schreibe bitte die Ergebnisse hier mit rein. Ich habe gerne Vergleichswerte von anderen Nutzern.


LG

Dennis

**Comment by DanielFuchs98** [comment]
Hallo Dennis,
wie besprochen, hier die Performance auf einer 200Mbit-Leitung zwischen zwei angemieteten Servern.

Direkt:
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 93.104.xxx.xxx port 49774 connected with 93.104.xxx.xxx port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   231 MBytes   193 Mbits/sec


Über VPNCloud:
------------------------------------------------------------
[  3] local 10.0.0.1 port 58388 connected with 10.0.0.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   192 MBytes   161 Mbits/sec

Sprich mit AES256 verliert man ca. 30Mbits, was für mich komplett in Ordnung ist.

VG
Daniel

**Comment by bmullan** [comment]
@DanielFuchs98 - thanks for those peformance numbers

A couple questions:

Was that using TUN or TAP?

Also, so I am reading your results right. 
Both tests using a 200Mbps link.

This is **with out Encryption**:

> [ID] Interval Transfer Bandwidth
> [3] 0.0-10.0 sec 231 MBytes **193 Mbits / sec**
> Via VPNCloud:

This is **with Encryption**?

> [3] local 10.0.0.1 port 58388 connected with 10.0.0.2 port 5001
> [ID] Interval Transfer Bandwidth
> [3] 0.0-10.0 sec 192 MBytes **161 Mbits / sec**

The results look quite good with encryption!

**Comment by DanielFuchs98** [comment]
@bmullan 
I´m using TAP-Devices for my setup. The two Servers are connected via an 200Mbps-link.

The first value is direct over eth0, without vpncloud. The second was with vpncloud and aes256-encryption.

> The results look quite good with encryption!

Yes! I was also surprised :)
