### ISSUE TITLE
is a vpncloud "mesh" supposed to be auto-learning?

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#41]
I have 3 nodes  A, B, C

**on A**
myvpn.net file lists 2 peers of both B and C

**on B**
myvpn.net file list only 1 peer of A

**on C**
myvpn.net file list only 1 peer of A

starting the vpn on A, B, C

A can ping B and C
and B can ping A
and C can ping A

_but  B cannot ping C_

If I add B as a Peer on C
and add C as a Peer on B
then ...  B and C can ping each other.

I'm trying to avoid having to edit config files on every node already in the VPN Mesh every time a new node joins the VPN mesh.

> **Automatic peer-to-peer meshing, no central servers**

I guess the above statement is still true but I was hoping that as long as B and C were both peered to A that B and C would auto-learn of each other and be able to ping each other.

This becomes valuable if I had 100 nodes in a working VPN Mesh and added 1 new Node to the mesh by Peering to ANY one or two Nodes already "in the mesh"...  that all of the other Nodes in the VPN Mesh would auto-learn of the presence of the new Node

This is somewhat related to Issue # https://github.com/dswd/vpncloud/issues/42
I read about "Beacons" but I was hoping that was for some extended purpose than what I was looking for.

Maybe I am misunderstanding something

**Comment by bmullan** [comment]
Again, maybe I either misconfigured something or misunderstand something but on this page:
https://github.com/dswd/vpncloud/blob/master/vpncloud.md

it says...

> All connected VpnCloud nodes will form a peer-to-peer network **and cross-connect automatically until the network is fully connected**. The nodes will periodically exchange information with the other nodes to signal that they are still active and to allow the automatic cross-connect behavior. There are some important things to note:

which again is why I was thinking that... 
as long as a NEW node trying to join an existing VPN Mesh was configured with at least 1 or more Peers that already were part of that VPN Mesh that the NEW Node would be auto-learned by all of the existing members of the VPN Mesh and that the NEW Node would auto-learn about all of them also.

**Comment by dswd** [comment]
Yes you are right, the nodes should learn the addresses of the other nodes and connect to them.
I don't know why this is not happening in your case. Maybe it just needs more time or there are too many nodes behind NATs.
You should be able to debug this looking at the logs.

**Comment by bmullan** [comment]
@dswd 

In the **example.net.disabled** example myvpn.net file it says:

> \# Address of a peer to connect to. The address should be in the form
> \# `addr:port`. If the node is not started, the connection will be retried
> \# periodically. This parameter can be repeated to connect to multiple peers.
> \# Note: Several entries can be separated by spaces.
> \#peers:
> \#  - node2.example.com:3210
> \#  - node3.example.com:3210

I had assumed this meant indicating the Node's PUBLIC IP addresses.

However,  in the [Documentation page](https://vpncloud.ddswd.de/docs/) and looking at [How to set up a peer-to-peer fully-meshed VPN between servers](https://medium.com/@matteocontrini/how-to-setup-a-peer-to-peer-fully-meshed-vpn-between-servers-249a9071e714)  he says...

> The following is a sample configuration for peers .
> 
> peers:
>   \- **privateip1**:3210
>   \- privateip2:3210

Maybe its  his use of the word "private" or "private ip" through out the rest of that Post where he says things like:

> _at some point you’ll want to set up a Virtual Private Network (VPN) between your servers, so that they’ll be able to contact each other with **custom **_private IP_** addresses (like 10.0.1.x)** through an encrypted network._

So (to me) that could be confusing... f_or the PEER config statement does it mean use the Public IP of the server (or VM) or does it mean the VPN ip address assigned to the Peer._   

> peers:
>   \- **privateip**1:3210

I've got to believe it means the Public IP of the Server/Node/VM

_Hope you see what I mean here as for people newly introduced to VpnCloud its examples and careful wording in documentation that keeps people from being frustrated by things not working?_

**Comment by dswd** [comment]
@bmullan 

The addresses you have to put as peers are the public ones. This means any address that can be used by the node to reach that peer will be fine, but usually this is the public IP.

The article you referring to is written by someone else and I can't change it. He has a special setup where all of his servers have a public IP and a private IP and both can be used to communicate between the servers. This is normally not the case. Usually private IPs mean NAT and can't be used to reach other peers (except when in the same NAT).

**Comment by bmullan** [comment]
@dswd 

Thanks... I know the article was written by someone else.   I just mentioned it so you knew what I was looking at.   His servers were all on Digital Ocean from what I gathered.

Brian
