### ISSUE TITLE
Additional config information & examples should be added about Beacons

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#42]
On the page describing Beacons there is no example commands or configurations:
https://vpncloud.ddswd.de/docs/beacons/

The section on **_Using Beacons_** only says:

> VpnCloud supports beacons via the **parameters --beacon-store, --beacon-load, and --beacon-interval.**
> 
> The interval is set in seconds and determines how often VpnCloud will search for beacons and write out its own beacon (if enabled via the other two parameters).
> 
> The store and load parameters enable beacon storing/loading and define a filename to store the beacon into or load the beacon from.
> 
> Instead of using files, **_VpnCloud also supports calling commands to store and load beacons. If the argument starts with a pipe character |, the rest of the argument is interpreted as a shell command which is passed to sh. In that command, the following variables can be used:_**

There is no mention of **_where the parameters --beacon-store, --beacon-load and --beacon-interval are used in a command or if they are added  to the "myvpn.net" config file_** somewhere?

There is also no example of how to get "_**VpnCloud also supports calling commands to store and load beacons**_"

I think it would help to expand this page of the documentation to describe examples of the various ways of using Beacons in VpnCloud.

**Comment by dswd** [comment]
You can use the "dash-dash" version as command line parameters or without a dash in the config file.

If you go to https://vpncloud.ddswd.de/docs/beacons/ and look on the left, there is a "examples" panel that leads to two complete usage examples.

**Comment by bmullan** [comment]
@dswd thanks your comment here in this issue helps clarify it:

> You can use the "dash-dash" version as command line parameters or without a dash in the config file.

I was already aware of [that link](https://vpncloud.ddswd.de/docs/beacons/dropbox/) but if you read that pages contents _**through the eyes of someone relatively new to VpnCloud**_ (like myself) its not clear where the dash-dash commands go?   

Also when you say:
> or without a dash in the config file.

In the example myvpn.net config file all of the sections begin with a **key-word** followed by one or more configuration statements for example for Peers:

> **peers:**
>   - node2.example.com:3210
>   - node3.example.com:3210

So to add the config statements for Beacons what would be the Keyword (an example would be even better.

_I'm just guessing but is it something like:_

**beacon-store:**
  - path/to/dropbox/beacon/folder/node1.beacon

And the webpage says for "beacon-load":

> Loading the beacons is a little bit more complex, as it requires reading multiple files at once

_So for the Beacon Load I'm not sure what the /etc/vpncloud/myvpn.net file statement might look like??_

**beacon-load:**
  - '|path/to/dropbox/beacon/folder/*.beacon'

thanks for any guidance...
Brian









 


Do they go in the /etc/vpncloud/myvpn.net or are they used on the CLI?

**Comment by dswd** [comment]
The config file version would be:
```
beacon-store: /path/to/file
beacon-load: "|cat path/to/dropbox/beacon/folder/*.beacon"
```
Note that there are no dashes like with the peers (dash means list entry).
Also note the double quotes when using the pipe character `|`. This is required because `|` has a special meaning.
This is all standard YAML, you can read it up at https://en.wikipedia.org/wiki/YAML

The CLI argument version would be:
```
$> vpncloud ... --beacon-store path/to/dropbox/beacon/folder/node1.beacon
$> vpncloud ... --beacon-load '|cat path/to/dropbox/beacon/folder/*.beacon'
```
Note the single quotes when using `*` to prevent that the bash expands that right away.

Whether you use CLI or config file version is up to you.

**Comment by bmullan** [comment]
@dswd 

Thanks so much for this info.   It might be helpful to add it to the Beacon page for others?

Also, from a Post I made on [LXD User Forum](https://discuss.linuxcontainers.org/) I got a reply back from one of the LXD Developers.

I know you probably don't follow LXD but they are working toward an LXD release that not only will have LXD daemon (and API) managing LXC containers but also KVM VM's all with a common API and CLI command structure..

So in essence when I need a VM instead of an LXD container I won't have to use Virsh or Virt-Manager any more  :-)

Anyway I am telling you this because all the Mesh VPNs I've looked at are either  TAP or TUN capable.

Only a few were able to work either way.   VpnCloud in this area is probably the MOST flexible of all that I have tried.

The LXD Developer told me that with the new release LXD will do away with using the LXDBR0 bridge to connect the Containers on a Server/Host to the Containers and instead:

> The forthcoming routed nic device type in LXD 3.19 may help with this.
> 
> It avoids the need for using a bridge entirely, and can optionally be used without specifying a parent interface.
> 
> You assign IPs statically to the device and then it sets up static routes on the host to the host side interface of the veth pair.
> 
> If you were running a routing daemon on the host you could then use those static routes to distribute them to other nodes.

This will be great because the extra configs on each Server/Host to "Route" the TUN end-point to/from the LXDBR0 bridge of the Containers was a pain and if you had alot of Servers/Hosts time-consuming unless of course you were an Ansible guru.

So up till now I tried to stick with a VPN TAP configuration.   But with that there is the impact of possibly more traffic over the Tunnel than using a Routed TAP tunnel interface would cause.

I don't know when that release of LXD is expected but  I don't think its that far off from what I've been seeing/hearing.

thanks again for VpnCloud and for your answers to my questions/issues.

Brian'

**Comment by dswd** [comment]
That sounds great. Please send me any writeup you are doing on this topic. As you noticed, documenting things for users that are not so tech savvy is not one of my strengths, so I am grateful for any help.

Also for your info: I added another working example to store beacons using Github Gists at https://vpncloud.ddswd.de/docs/beacons/github-gist/

**Comment by bmullan** [comment]
@dswd 
this looks great thanks...

> Also for your info: I added another working example to store beacons using Github Gists at https://vpncloud.ddswd.de/docs/beacons/github-gist/
