### ISSUE TITLE
Need more information about using a Bash script to save/load Beacon data?

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#43]
In the webpage about Using Beacons it says:
_
> Instead of using files, VpnCloud also supports calling commands to store and load beacons. **If the argument starts with a pipe character |, the rest of the argument is interpreted as a shell command which is passed to sh.** In that command, the following variables can be used:
> 
>     $begin: The prefix of the beacon
>     $end: The suffix of the beacon
>     $data: The inner data part of the beacon (do not use this without the prefix and the suffix)
>     $beacon: The full beacon with prefix and suffix.
> 
> The variables $data and $beacon can only be used when storing a beacon, not when searching for one during load._

Could you supply an example of such a _myvpn.net config statement_ along with a companion example Bash shell to demonstrate the usage?

I think I understand how those variables are referenced in some Bash script but do not understand how the script would return any data to VpnCloud?

**Comment by bmullan** [comment]
@dswd 
I did see where for PHP there is an example PHP script with example of how to call it to store or load a beacon

https://vpncloud.ddswd.de/docs/beacons/php-service/

The reason I asked about Bash was that I'm good with not a programmer but I'm good with Bash and I found some great example Bash scripts of using Bash to read/write indexed data to a MySQL db.

**https://blog.mclaughlinsoftware.com/2015/05/17/bash-arrays-mysql/**

So I figured I can modify some of those to do what might be required for VpnCloud's Beacon save/load process.

Brian

**Comment by dswd** [comment]
You can use this in your config:

```
beacon-store: "|/path/to/your/store/script.sh $beacon"
```
Your script will then be called with the full beacon as first parameter (`$1`).

Loading the beacon:
```
beacon-load: "|/path/to/your/load/script.sh"
```
Your script then has to print out the beacon to stdout (e.g. using `echo`).
