### ISSUE TITLE
Anything in this Government alert affect vpncloud

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#44]
I read [this article of the Government warning](https://www.forbes.com/sites/daveywinder/2020/01/13/us-government-critical-security-alert-upgrade-vpn-or-expect-continued-cyber-attacks/#16dec99a6f70) issued to vpn vendors and wondered if there was any impact to vpncloud.

**Comment by dswd** [comment]
Oh sorry, I didn't see the issue.
After a brief reading of the CVE, I think this whole story is about one specific commercial product with a serious flaw. The article somehow makes it sound like it is a general VPN problem. Anyhow, VpnCloud is not be affected.
