### ISSUE TITLE
Does or could VpnCloud support VPN NAT?

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#45]
I was reading _this **IBM** writeup_ on _**VPN NAT**_:
**[Network address translation for VPN](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_71/rzaja/rzajavpnnatex.htm)**

I'm still learning but I'd never heard of **VPN NAT** before and after reading the IBM article I could see use-cases for it.

**Comment by dswd** [comment]
NAT is not directly implemented by VpnCloud but you can configure it via Linux commands (see https://vpncloud.ddswd.de/docs/tutorial-tunneled-internet-access-with-nat/)

**Comment by bmullan** [comment]
@dswd 
The section of the **IBM** note I think is different and why its called "VPN NAT" was this:

> Unlike conventional network address translation (NAT), which changes the IP addresses in the security associations (SAs) that VPN requires to function, VPN NAT performs address translation before the SA validation by assigning an address to the connection when the connection starts.

**Comment by dswd** [comment]
Maybe I don't understand it fully, but I don't see the use case of doing NAT in the VPN vs. doing it via Linux. Anyhow, VpnCloud only supports the second option. Doing NAT inside the VPN would require parsing UDP and TCP and tracking payload connections which would duplicate kernel functionality and slow down the VPN.

**Comment by bmullan** [comment]
@dswd 
Okay... I thought it was for NAT'ing a VPN itself perhaps.   Like a VPN aggregation tool.

Brian
