### ISSUE TITLE
if I change from TAP to TUN what does this "warning" mean?

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#49]
@dswd - this is diff prob than I emailed you about...

as an experiment I changed 1 testbed from TAP to TUN then looking at Status I see:

$ **sudo service vpncloud@ciab status**
● vpncloud@ciab.service - VpnCloud network 'ciab'
   Loaded: loaded (/lib/systemd/system/vpncloud@.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-02-03 17:10:03 UTC; 2min 28s ago
     Docs: man:vpncloud(1)
 Main PID: 26406 (vpncloud)
    Tasks: 1 (limit: 4702)
   CGroup: /system.slice/system-vpncloud.slice/vpncloud@ciab.service
           └─26406 /usr/bin/vpncloud --config /etc/vpncloud/ciab.net --log-file /var/log/vpncloud-ciab.log --stats-file /var/log/vpncloud-ci

Feb 03 17:10:03 node1 systemd[1]: Started VpnCloud network 'ciab'.
Feb 03 17:10:03 node1 vpncloud[26406]: INFO - Reading config file '/etc/vpncloud/ciab.net'
Feb 03 17:10:03 node1 vpncloud[26406]: INFO - Opened device vpncloud0
Feb 03 17:10:13 node1 vpncloud[26406]: **_WARN - Port-forwarding: no router found_**
Feb 03 17:10:13 node1 vpncloud[26406]: INFO - New peer: 88.198.118.208:3210
Feb 03 17:10:13 node1 vpncloud[26406]: INFO - New peer: 45.37.56.251:1035
Feb 03 17:10:13 node1 vpncloud[26406]: INFO - New peer: 45.37.56.251:63234

I know what Port Forwarding is... but what does the above mean coming from VpnCloud Status?

thanks

**Comment by dswd** [comment]
Hi, sorry for the long delay.
This warning just means that port forwarding tried to find a router to talk to via UPnP but did not find one. This is normally no problem and even expected if you don't have a NAT router. You can disable the whole functionality by adding `--no-port-forwarding`

**Comment by dswd** [comment]
The latest version now only issues an info instead of a warning.
