### ISSUE TITLE
Providing i386 release

### ISSUE THREAD

**Issue by Chrisi-Bavaria** [dswd/vpncloud#50]
Hi,
I have a bunch of Alix boxes here. They have an AMD Geode i686 CPU, but it is only capable running 32Bit. It would be very convenient if the Debian repository could include a i386 release beside the amd64...

**Comment by dswd** [comment]
Please try the following package (unzip for deb file): 
[vpncloud_1.3.0_i386.zip](https://github.com/dswd/vpncloud/files/4233238/vpncloud_1.3.0_i386.zip)

Beware: this package contains some changes in master that are not released yet.

The next release will bring the i386 package automatically.

**Comment by Chrisi-Bavaria** [comment]
Hi,
did this change brake the toolchain? Because you released 1.3.0 in January, but in https://repo.ddswd.de/deb/pool/main/v/vpncloud/ still 1.2.1 is current. Is this intentionally?

**Comment by dswd** [comment]
Hi @Chrisi-Bavaria,
there is no automatic toolchain for the repo. I usually upload new versions a few weeks after putting them on github. This way apt-get users only get stable versions and people who install it manually from github are the testers.
This time, I just forgot to put 1.3.0 on the repo. Thanks for reminding me.

**Comment by bmullan** [comment]
Just curious so thought I'd ask.

Are most Distros dropping i386 support now?
