### ISSUE TITLE
add bind ip option

### ISSUE THREAD

**Issue by kuyagic** [dswd/vpncloud#51]
Server with more than 1 IP may need this feature
Please add the feature if possible
Thank you.

**Comment by DanielFuchs98** [comment]
Hello,
I've got the same requirement. On my setup I have two HAProxys in a Active-Passive installation via KeepAliveD. It would be nice if I can setup an Floating VPNCloud-IP.

Regards,
Daniel

**Comment by dswd** [comment]
Alright, I am already on it. It turns out to be a little more complex than I thought: VpnCloud normally opens 2 sockets (IPv4 and IPv6). If you specify one address however, there can be only one socket. This is quite a change in the code.

**Comment by DanielFuchs98** [comment]
Thanks for your quick Feedback. In my Setup it's important that I can add and remove IP's from th e VPNCloud-Interface via the IP command.
I think KeepAliveD use it in the background. At the moment my setup isn't at a production level, if you need an beta tester, I'm there :)

**Comment by dswd** [comment]
Wait there, I am not sure we are talking about the same thing. This issue is about restricting the VpnCloud service to only listen on one interface by binding it to the IP of that interface. What you are talking about sounds like something else.
If so, please open another issue and we could discuss there. VpnCloud might already support that functionality in some way.

**Comment by DanielFuchs98** [comment]
My fault, I will open a new issue

**Comment by dswd** [comment]
@kuyagic 
Please try the latest commit.

**Comment by kuyagic** [comment]
> 
> 
> @kuyagic
> Please try the latest commit.

Thank you.
I'll try it tomorrow

**Comment by dswd** [comment]
Oh, before you have to read the diff: I extended the `-l` parameter to accept PORT or IP:PORT (IP can be `*`, or any IPv4 or IPv6 address, defaults to `[::]`)
