### ISSUE TITLE
Supporting dynamic adding and removing of IP addresses

### ISSUE THREAD

**Issue by DanielFuchs98** [dswd/vpncloud#52]
I have an Setup with multiple Servers, that all connected via a VPNCloud connection.
In front of the servers are two LoadBalancers in Active-Passiv installation. The Active-Passive is done via KeepAliveD, which is dynamic adding an public IP to only on Service and also make the failover.
For Services that should be only reachable within the Cluster, it would be nice if VPNCloud support dynamic adding und removing an internal (floating) IP.

**Comment by dswd** [comment]
You can already add IPs to the vpncloud interface via ip (or ifconfig), the interface is not special in that way. Not sure if you can use that to establish a floating IP however. You might have some luck using TUN in learning switch mode and a very short dst-timeout. Then you could potentially add a new IP on one node and other nodes will learn this IP automatically. All untested, please tell me if you have any luck or run into problems.
