### ISSUE TITLE
dual stack

### ISSUE THREAD

**Issue by mschneider82** [dswd/vpncloud#53]
Hi,

I have an issue with ipv6 routing currently, unfortunately vpncloud is not switching to the ipv4 address, it would be nice to discover both addresses from a remote host and use the one with the lowest latency. Since ipv6 routing is may different and can be better or worse than v4.

Thanks
Matthias

**Comment by dswd** [comment]
I just release version 2 of VpnCloud which features a lot of code rewrite. Please reopen the ticket if the problem persists.
