### ISSUE TITLE
Error when trying to start service - Could not generate persistent MAC address

### ISSUE THREAD

**Issue by dpedoneze** [dswd/vpncloud#55]
Hello! I'm not sure if this is the right place to open this issue, but I'm having a problem with one server (the others are just fine) when I'm trying to start the vpncloud service.

I'm using the [vpncloud_0.9.1_xenial_amd64.deb](https://github.com/dswd/vpncloud/releases/download/v0.9.1/vpncloud_0.9.1_xenial_amd64.deb) package (because I'm running a Ubuntu 16.04 inside a VM).

```
ubuntu sudo[14864]: pam_unix(sudo:session): session closed for user root
ubuntu sudo[15132]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/sbin/service vpncloud@myvpn start
ubuntu sudo[15132]: pam_unix(sudo:session): session opened for user root by root(uid=0)
ubuntu systemd[1]: Starting VpnCloud network 'myvpn'...
ubuntu vpncloud[15163]: INFO - Reading config file '/etc/vpncloud/myvpn.net'
ubuntu vpncloud[15163]: INFO - Opened device vpncloud0
ubuntu systemd-udevd[15166]: Could not generate persistent MAC address for vpncloud0: No such file or directory
ubuntu systemd[1]: vpncloud@myvpn.service: Start operation timed out. Terminating.
ubuntu systemd[1]: Failed to start VpnCloud network 'myvpn'.
```

The main message is **Could not generate persistent MAC address for vpncloud0: No such file or directory**.

I'm using the example `.net` file on this and others servers, so I don't think that's the problem. 

Also, thanks for the awesome work @ vpncloud!!

**Comment by dpedoneze** [comment]
Stange update, I don't think the main error is **Could not generate persistent MAC address for vpncloud0: No such file or directory.**, because after looking into other servers syslog, I found:

```
22 systemd[1]: Starting VpnCloud network 'myvpn'...
22 vpncloud[15903]: INFO - Reading config file '/etc/vpncloud/myvpn.net'
22 vpncloud[15903]: INFO - Opened device vpncloud0
22 systemd-udevd[15906]: Could not generate persistent MAC address for vpncloud0: No such file or directory
25 vpncloud[15903]: WARN - Port-forwarding: no router found
25 vpncloud[15903]: INFO - Running process as daemon
25 systemd[1]: vpncloud@myvpn.service: Failed to parse PID from file /run/vpncloud-myvpn.pid: Invalid argument
25 systemd[1]: Started VpnCloud network 'myvpn'.
```

Where it shows the same **Could not generate persistent MAC address for vpncloud0: No such file or directory.**, and after that it **Running process as daemon** instead of **Start operation timed out. Terminating.**

---

Yesterday I luckily managed to make it work, today morning I stopped it and when I tried to start the error pops up again and I cant start the vpncloud anymore on this machine 😞

**Comment by dpedoneze** [comment]
So.. running the command by myself - and not using systemd/systemctl the vpn started:

```
/usr/bin/vpncloud --config /etc/vpncloud/%i.net --daemon --verbose --log-file /var/log/vpncloud-%i.log --stats-file /var/log/vpncloud-%i.stats --pid-file /run/vpncloud-%i.pid
```

```
INFO - Reading config file '/etc/vpncloud/%i.net'
DEBUG - Config: Config { device_type: Tap, device_name: "vpndevice%d", device_path: None, ifup: Some("ifconfig $IFNAME 10.0.2.20/24 mtu 1400"), ifdown: Some("ifconfig $IFNAME down"), crypto: AES256, shared_key: Some("XXXXX"), magic: Some("12345678"), port: PORT, peers: ["ip_A:PORT", "ip_B:PORT", "ip_C:PORT", "ip_D:PORT"], peer_timeout: 600, keepalive: None, mode: Normal, dst_timeout: 300, subnets: ["10.0.2.0/24"], port_forwarding: true, daemonize: true, pid_file: Some("/run/vpncloud-%i.pid"), stats_file: Some("/var/log/vpncloud-%i.stats"), user: Some("root"), group: Some("root") }
INFO - Opened device vpncloud0
DEBUG - http scheme
ERROR - Port-forwarding: failed to find router: HTTP error: Connection timed out (os error 110)
DEBUG - Running script: "sh" "-c" "ifconfig $IFNAME 10.0.2.20/24 mtu 1400"
DEBUG - Connecting to "ip_A:PORT"
DEBUG - Sending Init(stage=0, node_id=nodeID, [10.0.2.0/24]) to ip_A:PORT
DEBUG - Connecting to "ip_B:PORT"
DEBUG - Sending Init(stage=0, node_id=nodeID, [10.0.2.0/24]) to ip_B:PORT
DEBUG - Connecting to "ip_C:PORT"
DEBUG - Sending Init(stage=0, node_id=nodeID, [10.0.2.0/24]) to ip_C:PORT
DEBUG - Connecting to "ip_D:PORT"
DEBUG - Sending Init(stage=0, node_id=nodeID, [10.0.2.0/24]) to ip_D:PORT
INFO - Running process as daemon
```

Of course this isn't the best way since if the VM drops it won't recover after the reboot, but It might help to discover why it worked outside the systemd (229 - the same for the 4 VMs)

---

Checking the default timeout for systemd, i found out it's **5min** so this _might not_ be root the problem: 

```
systemctl show vpncloud.service

TimeoutStartUSec=5min
TimeoutStopUSec=5min
RuntimeMaxUSec=infinity
```

**Comment by dpedoneze** [comment]
It seems not to be a _vpncloud_ error but a timeout from somewhere else, so I'm closing this issue. Thanks!

**Comment by dswd** [comment]
It might be related to this line
`ERROR - Port-forwarding: failed to find router: HTTP error: Connection timed out (os error 110)`

If your router somehow accepts the connection but just blocks it instead of answering you might run into the 5 min systemd timeout as this happens before going into daemon mode (if I remember correctly).

So you might want to disable port forwarding in vpncloud to remove this potential cause.

**Comment by dpedoneze** [comment]
Hi dswd, thanks for answering! 

It fitted like a glove! I've update de service file including the `--no-port-forwarding` flag.

Thanks a million!
