### ISSUE TITLE
vpncloud0 with no ip address

### ISSUE THREAD

**Issue by snoep** [dswd/vpncloud#59]
Hi
Worked with a long time - no issues - with vpncloud 1.0.0 and upgraded recently to 1.3.1. Starting vpncloud results in the following message in systemctl status vpncloud
ERROR - Failed to execute script "ifconfig $IFNAME <ip/mask> mtu 1400": Operation not permitted (os error 1)
Manual adding the ip works, however I'm not sure what to change where to fix this permanent. Any suggestions?
Ubuntu 18.04.4 LTS

Thanks
Paul

**Comment by dswd** [comment]
Hi Paul,

this seems to be a problem with the permissions. Please post the contents of `/lib/systemd/system/vpncloud@.service` and your vpncloud network config (leave out the secret key and any IPs).

**Comment by snoep** [comment]
Thanks for the prompt reply, please find below the requested info


/lib/systemd/system/vpncould@.service
`[Unit]
Description=VpnCloud network '%I'
After=network-online.target
Wants=network-online.target
Documentation=man:vpncloud(1)

[Service]
Type=simple
ExecStart=/usr/bin/vpncloud --config /etc/vpncloud/%i.net --log-file /var/log/vpncloud-%i.log --stats-file /var/log/vpncloud-%i.stats
WorkingDirectory=/etc/vpncloud
RestartSec=5s
Restart=on-failure
LimitNPROC=10
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ReadWritePaths=/var/log
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw

[Install]
WantedBy=multi-user.target

and the network config, adapted to hide the "secret stuff"
listen: <high port>
peers:
   - <peer>:<high port>
peer_timeout: 600
magic: "magic"
shared_key: "key"
crypto: aes256
device_name: "vpncloud%d"
device_type: tap
mode: normal
subnets:
  - <subnet>
ifup: "ifconfig $IFNAME <peer ip/mask> mtu 1400"
ifdown: "ifconfig $IFNAME down"
pid_file: "/var/run/vpncloud"

`

**Comment by dswd** [comment]
Just to be sure: Is the `<peer ip/mask>` a placeholder you added instead of your actual contents or is that literally in the command?

**Comment by snoep** [comment]
it is a placeholder. Peer is an ip address like 1.2.3.4/24, ditto for the highport, which is in the config like 55555, or subnet which is like 1.2.3.0/24.
It worked like a charm using vpncloud 1.0.0 - besides the setting Port -> Listen nothing has changed.

**Comment by dswd** [comment]
Can you prepend `whoami;` to the ifup command? Like this `ifup: "whoami;ifconfig ...`
You should see the result in the output of `sudo systemctl status vpncloud@NAME` where NAME is your config file name (without .net).

**Comment by snoep** [comment]
If I do so, below the output

ERROR - Failed to execute script "whoami;ifconfig $IFNAME 10.1.1.101/24 mtu 1400": Operation not permitted (os error 1)

vpncloud0 remains at 1500 bytes, vpncloud runs as root
ps -ef | grep vpncloud
root     28077     1 90 15:17 ?        00:01:46 /usr/bin/vpncloud --config /etc/vpncloud/vpn.net --log-file /var/log/vpncloud-vpn.log --stats-file /var/log/vpncloud-vpn.stats

vpncloud-vpn.log contains simliar output as systemctl status vpncloud@vpn

**Comment by dswd** [comment]
You can try to remove the following lines
```
LimitNPROC=10
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ReadWritePaths=/var/log
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
```

Maybe it works then. However I got the exact same setup and it works for me.

**Comment by snoep** [comment]
hmm.
Changed /lib/systemd/system/vpncloud@.service as you suggested
systemctl daemon-reload
systemctl restart vpncloud@vpn

ERROR - Script returned with error: Some(255)

I'm not sure where I can find the 'Some' :)

I will do some more testing on other hosts too. This is cloudmachine where the supplier states it is an Ubuntu 18.04.4 LTS ,

**Comment by snoep** [comment]
I checked syslog and noticed now:
systemd[1]: Failed to set devices.allow on /system.slice/system-vpncloud.slice/vpncloud@oanet.service: Operation not permitted

A google resulted in the link below
https://askubuntu.com/questions/747023/systemd-fails-to-start-openvpn-in-lxd-managed-16-04-container/747146#747146

due to the similarities I tried this and it worked....
As per the fix I changed the nproc=infinity to nproc=100 and that works also.

Many thanks for prompt responses. I'm a happy camper using vpncloud.

Cheers 
paul

**Comment by dswd** [comment]
Oh that's great.
So you left all the lines untouched and just changed `LimitNPROC` from 10 to 100? Is that correct?

**Comment by dswd** [comment]
Oh and I have to fix that `Some` error. That is from vpncloud.

**Comment by snoep** [comment]
Initially I changed the systemctl edit vpncloud@.service line from infinity to 100 and tested, then I removed all the lines from systemctl edit vpncloud@.service and changed the line limitNPROC=10 in /lib/systemd/system/vpncloud@.service to limitNPROC=100 and systemctl daemon-reload; systemctl restart vpncloud@vpn

That worked also!.
