### ISSUE TITLE
Startup scripts and race conditions

### ISSUE THREAD

**Issue by jwr** [dswd/vpncloud#60]
I've been using vpncloud for years now, I rarely find a piece of software which is so trouble-free. Excellent work!

Recently I needed to set up a database cluster (RethinkDB) on a private network managed by vpncloud, using Ubuntu 18.04.4 LTS. But there seems to be a problem with startup: the database is set to depend on vpncloud service, but starts up before the interfaces have actually come up.

Is there an option to make the vpncloud service wait for the interface to come up (with a timeout), before it tells systemd that it's done?

**Comment by dswd** [comment]
Please try the latest commit. There was actually a problem with the startup script.

**Comment by jwr** [comment]
Thank you. I am afraid I have no easy way to try without a released .deb, so I guess I'll wait. In the meantime, I worked around the problem by using a script that calls `ifdata` to wait for the interface. It turned out that it isn't enough to wait for the interface being up, I had to wait for it to get an IP address, which happens later.

**Comment by dswd** [comment]
I just released 1.4.0. I will push the packages to the repo in a few days. Please check out that deb file in github in the meantime.

**Comment by jwr** [comment]
I tried it and I can confirm that the problem is gone. I can remove my workaround with 1.4.0.

Thank you for your work!

**Comment by jwr** [comment]
I tried it and I can confirm that the problem is gone. I can remove my workaround with 1.4.0.

Thank you for your work!

**Comment by dswd** [comment]
You are welcome. Also thanks a lot for your donation.
