### ISSUE TITLE
Option for not encrypting packets? 

### ISSUE THREAD

**Issue by sandreae** [dswd/vpncloud#69]
Hi, 

I'm testing using vpncloud to setup connections between a group of peers who are streaming live uncompressed audio over udp. For this case encryption isn't a priority, but latency is. I wondered if there is a setting to run vpncloud without encryption? Is this in fact the default setting before the different encryption methods are enabled? 

Sam

**Comment by dswd** [comment]
Yes, unencrypted mode is the default if you are not setting any crypto method and no shared key.

**Comment by sandreae** [comment]
Ok, great, thanks.

Do you have any other recommendations for optimizing the stream? I wondered if changing to TUN / router makes any difference in this regard for example.

**Comment by dswd** [comment]
TUN might be a little better but we are talking about 1 or 2 microseconds, not milliseconds. You should keep the MTU down to 1400 to avoid fragmentation. Otherwise, I don't know any optimizations. If you find out anything that helps (maybe using sysctl settings or ionice) please post it.

**Comment by sandreae** [comment]
OK, thanks, will do!

**Comment by TalalMash** [comment]
Increasing socket send buffer `net.core.rmem_max=26214400` seems to be essential with VMs.
Increased from 1.2Gbit to 3.1Gbit with ESXi (paravirt) VM vs 2Gbit with WG (no tweaking)
