### ISSUE TITLE
More regularly update stats file

### ISSUE THREAD

**Issue by sandreae** [dswd/vpncloud#70]
I'd like to be able to monitor a list of connected peers in near real time. Currently I am watching the stats file to get this data, but it only updates at fairly long intervals.

Am I missing an obvious config which sets update interval for the stats file?

**Comment by dswd** [comment]
The stats are being sent out every 60 seconds. That value is currently hard-coded and can't be changed. I could add an option for it but keep in mind that sending out the stats will reset some counters. So pushing out every second will not only have a performance impact but also reduce the stats quality as you have to calculate an average on your own.

For monitoring multiple nodes at once, there is support for sending monitoring data to a statsd server. The feature is pretty new, so please give me some feedback when you use it.

**Comment by sandreae** [comment]
OK, thanks for the info. Is there any documentation of the feature you mentioned?

**Comment by dswd** [comment]
The parameters `--statsd-prefix` and `--statsd-server` are documented but the whole feature does not have an article of its own. The feature came out of #57, you could get some details from that issue.

**Comment by sandreae** [comment]
Great, thanks. I'll do that and let you know how it goes.

**Comment by sandreae** [comment]
I managed to get statsd setup, it went quite smoothly, thanks for adding that as a feature it's going to be v useful.

Is it possible to set the relevant statsd params in the config file? I tried using the related prefix keys but it didn't seem to work.

**Comment by dswd** [comment]
What kind of parameters are you missing? The statsd-server option takes the servername and port number and the statsd-prefix option adds a fixed prefix to all reported values to distinguish multiple instances.

**Comment by sandreae** [comment]
I'm not missing anything, I mean is it possible to set statsd-server and statsd-prefix in the vpncloud config file? Like so:

/etc/vpncloud/mynet.net

`statsd-server: x.x.x.x`
`statsd-prefix: peer1`

It didn't seem to work for me, whereas parameters `--statsd-prefix` and `--statsd-server` does.

**Comment by dswd** [comment]
For the config files, the options are named with underscore, not minus. (`statsd_server` and `statsd_prefix`)
Sorry, this is not documented.

**Comment by sandreae** [comment]
Thanks!
